print("This Is Youtube Channel Name Generator ;) ")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print()
name = input("What Is Your Nickname?\n")
print()
Description = input("What Is Your Channel About?\n")
print()
print("You Can Name It " + "(" +Description + " " + "with " + name + ") and Good Luck With Content Creating")
print()