print ("Signing you up!")
print ("~~~~~~~~~~~~~~~")
print()
Name = input("What Is Your Name?\n")
print()
Phone = input("Enter Your Phone Number\n")
print()
Gmail = input("Enter Your Gmail\n")
print()
Username = input("Choose a username\n")
print()
Birthdate = input("Enter your Birthdate\n")
print()
print ("You Have Signed Up Successfully")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print()
print("Your Name is " + Name)
print("Your Phone Number is " + Phone)
print("Your Gmail is " + Gmail)
print("Your Username is " + Username)
print("You Have Born in " + Birthdate)
print()
print()