print("Digits Plusser")
print("~~~~~~~~~~~~~~")
print()
entrance = input('Enter Two Digit Number\n')
equal = int (entrance [0])+int (entrance [1])
print()
print("The Sum Of The Two Digits Equals " + str (equal))
print()
print()