print('Area Calcaulator')
print('~~~~~~~~~~~~~~~~')
print()
str_Length = input("Enter The Length:\n")
print()
str_width = input("Enter The Width:\n")
print()
float_Length = float(str_Length)
float_width = float(str_width)
area = str(float_Length*float_width)
print("The Area is " + area)
print()
print()