print('The Year You Have Born In Calcaulator')
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print()
years_old = input("Plese Enter How Old Are You:\n")
print()
year = 2024-int(years_old)
str_year = str(year)
print("You Have Born in " + str_year)
print()
print()